common: &shared
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5433
  username: lsmith
  password:

development:
  database: ticket_mule_development
  <<: *shared

test:
  database: ticket_mule_test
  <<: *shared

production:
  database: ticket_mule_production
  <<: *shared
